# Generated by Django 4.2.2 on 2023-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="goal",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
