# Generated by Django 4.2.2 on 2023-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workout_app",
            "0003_alter_exerciseset_distance_alter_exerciseset_reps_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="goal",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
