# Generated by Django 4.2.2 on 2023-06-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workout_app", "0005_alter_exercise_goal_alter_exerciseset_distance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciseset",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="exerciseset",
            name="workout",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="goal",
            field=models.IntegerField(
                choices=[(0, "Repetitions"), (2, "Distance")], default=0
            ),
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercise_workout_exercise",
                        to="workout_app.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_workout_exercise",
                        to="workout_app.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="workout_exercise",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_exercise_exercise_set",
                to="workout_app.workoutexercise",
            ),
        ),
    ]
