# Generated by Django 4.2.2 on 2023-06-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout_app", "0007_alter_exerciseset_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_exercise",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="time",
            field=models.CharField(blank=True, default="00:00:00:0", null=True),
        ),
    ]
