# Generated by Django 4.2.2 on 2023-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_app", "0002_alter_exercise_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseset",
            name="distance",
            field=models.FloatField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="reps",
            field=models.IntegerField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="time",
            field=models.IntegerField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="weight",
            field=models.IntegerField(blank=True, default="", null=True),
        ),
    ]
