# Generated by Django 4.2.2 on 2023-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_app", "0004_alter_exercise_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="goal",
            field=models.IntegerField(
                choices=[(0, "Strength"), (1, "Cardio")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="distance",
            field=models.FloatField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="reps",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="time",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="weight",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
